// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// kfks_cpp
Rcpp::List kfks_cpp(const arma::mat& A, const arma::mat& C, const arma::mat& R, const arma::mat& Q, const arma::mat& data_wide, const arma::mat& P1, double dim_state, bool only_ll);
RcppExport SEXP _rmfd4dfm_kfks_cpp(SEXP ASEXP, SEXP CSEXP, SEXP RSEXP, SEXP QSEXP, SEXP data_wideSEXP, SEXP P1SEXP, SEXP dim_stateSEXP, SEXP only_llSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type data_wide(data_wideSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P1(P1SEXP);
    Rcpp::traits::input_parameter< double >::type dim_state(dim_stateSEXP);
    Rcpp::traits::input_parameter< bool >::type only_ll(only_llSEXP);
    rcpp_result_gen = Rcpp::wrap(kfks_cpp(A, C, R, Q, data_wide, P1, dim_state, only_ll));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rmfd4dfm_kfks_cpp", (DL_FUNC) &_rmfd4dfm_kfks_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_rmfd4dfm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
