# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Kalman filter smoother
#'
#' @param A n x r observation system matrix
#' @param C r x r state transition matrix
#' @param R n x n noise covariance matrix
#' @param Q q x q error covariance matrix
#' @param data_wide n x T data matrix
#' @param P1 r x r initial state variance matrix
#' @param dim_state value r
#' @param only_ll boolean, return only log-likelihood calculated with KFss
#'
#' @keywords internal
kfks_cpp <- function(A, C, R, Q, data_wide, P1, dim_state, only_ll) {
    .Call(`_rmfd4dfm_kfks_cpp`, A, C, R, Q, data_wide, P1, dim_state, only_ll)
}

lyapunov_cpp <- function(A, Q, P, lambda_r, lambda_i, stop_if_non_stable) {
    .Call(`_rmfd4dfm_lyapunov_cpp`, A, Q, P, lambda_r, lambda_i, stop_if_non_stable)
}

lyapunov_Jacobian_cpp <- function(A, Q, P, dA, dQ, J, lambda_r, lambda_i, stop_if_non_stable) {
    .Call(`_rmfd4dfm_lyapunov_Jacobian_cpp`, A, Q, P, dA, dQ, J, lambda_r, lambda_i, stop_if_non_stable)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_rmfd4dfm_RcppExport_registerCCallable', PACKAGE = 'rmfd4dfm')
})
